name: Example pynt yml 
on: 
  workflow_dispatch:
    inputs: 
      comment: 
        type: string 
        default: "Pynt API Security tests"

env:
  PYNT_CREDENTIALS: ${{ secrets.YOURPYNTID }}

jobs:
 api-security:
  runs-on: ubuntu-latest

  steps: 
    - name: install pynt cli
      run: | 
        python3 -m pip install --upgrade pyntcli 
    - name: get my collection 
      run: | 
        curl https://github.com/sseenivasan89/pynt/blob/main/myCollection.json -o myCollection.json     
    - name: run pynt with newman integration 
      run: | 
        pynt newman --collection myCollection.json --reporters
